// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using Microsoft.AspNetCore.Mvc;
using Storm.Api.Extensions;

namespace Sample;

public partial class C
{
	[global::Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute<global::Storm.Api.Dtos.Response>(200, "application/json")]
	public partial async global::System.Threading.Tasks.Task<global::Microsoft.AspNetCore.Mvc.ActionResult<global::Storm.Api.Dtos.Response>> M()
	{
		return await InternalWrapForError<global::Storm.Api.Dtos.Response>(async () =>
		{
			return await Services.ExecuteAction<global::Sample.Q, global::Sample.P, global::Storm.Api.Dtos.Response>(new());
		});
	}

}
