// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using Microsoft.AspNetCore.Mvc;
using Storm.Api.Extensions;

namespace Sample;

public partial class C
{
	[global::Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute<global::System.IO.Stream>(200, "application/json")]
	public partial async global::System.Threading.Tasks.Task<global::Microsoft.AspNetCore.Mvc.IActionResult> M()
	{
		return await FileAction<global::Sample.Q, global::Storm.Api.Unit>(global::Storm.Api.Unit.Default);
	}

}
