// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using Microsoft.AspNetCore.Mvc;
using Storm.Api.Extensions;

namespace Sample;

public partial class C
{
	[global::Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute<global::Storm.Api.Dtos.Response<string>>(200, "application/json")]
	public partial async global::System.Threading.Tasks.Task<global::Microsoft.AspNetCore.Mvc.ActionResult<global::Storm.Api.Dtos.Response<string>>> FromFileA()
	{
		return await InternalWrapForError<global::Storm.Api.Dtos.Response<string>>(async () =>
		{
			string actionResult = await Services.ExecuteAction<global::Sample.Q1, global::Storm.Api.Unit, string>(global::Storm.Api.Unit.Default);
			return new global::Storm.Api.Dtos.Response<string>
			{
				IsSuccess = true,
				Data = actionResult,
			};
		});
	}

	[global::Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute<global::Storm.Api.Dtos.Response<int>>(200, "application/json")]
	public partial async global::System.Threading.Tasks.Task<global::Microsoft.AspNetCore.Mvc.ActionResult<global::Storm.Api.Dtos.Response<int>>> FromFileB()
	{
		return await InternalWrapForError<global::Storm.Api.Dtos.Response<int>>(async () =>
		{
			int actionResult = await Services.ExecuteAction<global::Sample.Q2, global::Storm.Api.Unit, int>(global::Storm.Api.Unit.Default);
			return new global::Storm.Api.Dtos.Response<int>
			{
				IsSuccess = true,
				Data = actionResult,
			};
		});
	}

}
