// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using Microsoft.AspNetCore.Mvc;
using Storm.Api.Extensions;

namespace Sample;

public partial class KitchenSinkController
{
	[global::Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute<global::Storm.Api.Dtos.Response>(200, "application/json")]
	public partial async global::System.Threading.Tasks.Task<global::Microsoft.AspNetCore.Mvc.ActionResult<global::Storm.Api.Dtos.Response>> Authed(int a, int b)
	{
		return await InternalWrapForError<global::Storm.Api.Dtos.Response>(async () =>
		{
			global::Storm.Api.Unit actionResult = await Services.ExecuteAction<global::Sample.AuthedQuery, global::Sample.SumParameter, global::Storm.Api.Unit>(new()
			{
				A = a,
				B = b,
			});
			return new global::Storm.Api.Dtos.Response
			{
				IsSuccess = true,
			};
		});
	}

	[global::Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute<global::System.IO.Stream>(200, "image/png")]
	public partial async global::System.Threading.Tasks.Task<global::Microsoft.AspNetCore.Mvc.IActionResult> File()
	{
		return await FileAction<global::Sample.FileQuery, global::Storm.Api.Unit>(global::Storm.Api.Unit.Default);
	}

	[global::Microsoft.AspNetCore.Http.EndpointSummaryAttribute(@"Greets the caller")]
	[global::Microsoft.AspNetCore.Http.EndpointDescriptionAttribute(@"Error Codes:
- ShortCode1: 
- ShortCode2: desc 2
- SumError: sum failed

A friendly greeting endpoint.

")]
	[global::Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute<global::Storm.Api.Dtos.Response<global::Sample.HelloResponse>>(200, "application/json")]
	[global::Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute<global::Storm.Api.Dtos.Response>(400, "application/problem+json", Description = @"bad")]
	[global::Storm.Api.OpenApis.OpenApiErrorCodesAttribute("ShortCode1", "ShortCode2", "SumError")]
	public partial async global::System.Threading.Tasks.Task<global::Microsoft.AspNetCore.Mvc.ActionResult<global::Storm.Api.Dtos.Response<global::Sample.HelloResponse>>> Hello(string name)
	{
		return await InternalWrapForError<global::Storm.Api.Dtos.Response<global::Sample.HelloResponse>>(async () =>
		{
			global::Sample.HelloResponse actionResult = await Services.ExecuteAction<global::Sample.HelloQuery, global::Sample.HelloParameter, global::Sample.HelloResponse>(new()
			{
				Name = name,
			});
			return new global::Storm.Api.Dtos.Response<global::Sample.HelloResponse>
			{
				IsSuccess = true,
				Data = actionResult,
			};
		});
	}

	[global::Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute<global::Storm.Api.Dtos.Response>(200, "application/json")]
	public partial async global::System.Threading.Tasks.Task<global::Microsoft.AspNetCore.Mvc.ActionResult<global::Storm.Api.Dtos.Response>> Raw(string name)
	{
		return await InternalWrapForError<global::Storm.Api.Dtos.Response>(async () =>
		{
			return await Services.ExecuteAction<global::Sample.RawQuery, global::Sample.HelloParameter, global::Storm.Api.Dtos.Response>(new()
			{
				Name = name,
			});
		});
	}

	[global::Microsoft.AspNetCore.Http.EndpointDescriptionAttribute(@"Error Codes:
- SumError: sum failed

")]
	[global::Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute<global::Storm.Api.Dtos.Response<int>>(200, "application/json")]
	[global::Storm.Api.OpenApis.OpenApiErrorCodesAttribute("SumError")]
	public partial async global::System.Threading.Tasks.Task<global::Microsoft.AspNetCore.Mvc.ActionResult<global::Storm.Api.Dtos.Response<int>>> Sum(int a, int b)
	{
		return await InternalWrapForError<global::Storm.Api.Dtos.Response<int>>(async () =>
		{
			int actionResult = await Services.ExecuteAction<global::Sample.SumQuery, global::Sample.SumParameter, int>(new()
			{
				A = a,
				B = b,
			});
			return new global::Storm.Api.Dtos.Response<int>
			{
				IsSuccess = true,
				Data = actionResult,
			};
		});
	}

}
