// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using Microsoft.AspNetCore.Mvc;
using Storm.Api.Extensions;

namespace Sample;

public partial class C
{
	[global::Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute<global::Storm.Api.Dtos.Response<int>>(200, "application/json")]
	public partial async global::System.Threading.Tasks.Task<global::Microsoft.AspNetCore.Mvc.ActionResult<global::Storm.Api.Dtos.Response<int>>> M(int a, int b)
	{
		return await InternalWrapForError<global::Storm.Api.Dtos.Response<int>>(async () =>
		{
			int actionResult = await Services.ExecuteAction<global::Sample.Q, global::Sample.P, int>(new()
			{
				A = a,
				B = b,
			});
			return new global::Storm.Api.Dtos.Response<int>
			{
				IsSuccess = true,
				Data = actionResult,
			};
		});
	}

}
