// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using Microsoft.AspNetCore.Mvc;
using Storm.Api.Extensions;

namespace Sample;

public partial class C
{
	[global::Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute<global::Storm.Api.Dtos.Response>(200, "application/json")]
	public partial async global::System.Threading.Tasks.Task<global::Microsoft.AspNetCore.Mvc.ActionResult<global::Storm.Api.Dtos.Response>> M(global::Sample.Body payload)
	{
		return await InternalWrapForError<global::Storm.Api.Dtos.Response>(async () =>
		{
			global::Storm.Api.Unit actionResult = await Services.ExecuteAction<global::Sample.Q, global::Sample.P, global::Storm.Api.Unit>(new()
			{
				Data = payload,
			});
			return new global::Storm.Api.Dtos.Response
			{
				IsSuccess = true,
			};
		});
	}

}
