// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using Microsoft.AspNetCore.Mvc;
using Storm.Api.Extensions;

namespace Sample;

public partial class GreetController
{
	[global::Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute<global::Storm.Api.Dtos.Response<string>>(200, "application/json")]
	public partial async global::System.Threading.Tasks.Task<global::Microsoft.AspNetCore.Mvc.ActionResult<global::Storm.Api.Dtos.Response<string>>> Greet(string name)
	{
		return await InternalWrapForError<global::Storm.Api.Dtos.Response<string>>(async () =>
		{
			string actionResult = await Services.ExecuteAction<global::Sample.GreetQuery, global::Sample.GreetParameter, string>(new()
			{
				Name = name,
			});
			return new global::Storm.Api.Dtos.Response<string>
			{
				IsSuccess = true,
				Data = actionResult,
			};
		});
	}

}
