using Microsoft.CodeAnalysis.CSharp;
using Storm.Api.SourceGenerators.Bases;
using SymbolDisplayFormat = Microsoft.CodeAnalysis.SymbolDisplayFormat;

namespace Storm.Api.SourceGenerators.ActionMethods;

internal class CodeGenerator
{
	private readonly GeneratorContext _context;
	private readonly string _generatedCodeAttribute;

	public CodeGenerator(GeneratorContext context, string generatedCodeAttribute)
	{
		_context = context;
		_generatedCodeAttribute = generatedCodeAttribute;
	}

	public string Generate()
	{
		CodeBuilder builder = new();

		builder.AddLine("// <auto-generated />");
		builder.AddLine("#nullable enable");
		builder.AddLine("using System.CodeDom.Compiler;");
		builder.AddLine("using Microsoft.AspNetCore.Mvc;");
		builder.AddLine("using Storm.Api.Extensions;");
		builder.AddLine();
		if (_context.Namespace is not null)
		{
			builder.AddLine($"namespace {_context.Namespace};");
		}
		builder.AddLine();
		builder.AddLine($"{SyntaxFacts.GetText(_context.ClassAccessibility)} partial class {_context.ClassName}");
		builder.AddLine("{").Indent();
		foreach (MethodContext method in _context.Methods)
		{
			builder.Add($"{SyntaxFacts.GetText(_context.ClassAccessibility)} partial async {method.ReturnType} {method.Name}(");
			builder.Add(string.Join(", ", method.Arguments.Select(p => $"{p.Type} {p.Name}")));
			builder.AddLine(")");
			builder.AddLine("{").Indent();

			if (method.Type is ActionType.File)
			{
				OutputForFile(builder, method);
			}
			else if (method.Type is ActionType.Unit)
			{
				OutputForUnit(builder, method);
			}
			else if (method.Type is ActionType.Response)
			{
				OutputForResponse(builder, method);
			}
			else if (method.Type is ActionType.Regular)
			{
				OutputForRegular(builder, method);
			}

			builder.Unindent().AddLine("}");

			builder.AddLine();
		}
		builder.Unindent().AddLine("}");

		return builder.Code();
	}

	private void OutputForUnit(CodeBuilder builder, MethodContext method)
	{
		builder.AddLine($"return await InternalWrapForError<{_context.Types.Response.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(async () =>");
		builder.AddLine("{").Indent();

		builder.Add($"{method.ActionResultType} actionResult = await Services.ExecuteAction<{method.ActionType}, {method.ActionParameterType}, {method.ActionResultType}>(");
		OutputActionParameterMapping(builder, method);
		builder.AddLine(");");

		builder.AddLine($"return new {_context.Types.Response.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}");
		builder.AddLine("{").Indent();
		builder.AddLine("IsSuccess = true,");
		builder.Unindent().AddLine("};");

		builder.Unindent().AddLine("});");
	}

	private void OutputForResponse(CodeBuilder builder, MethodContext method)
	{
		builder.AddLine($"return await InternalWrapForError<{method.ActionResultType}>(async () =>");
		builder.AddLine("{").Indent();

		builder.Add($"return await Services.ExecuteAction<{method.ActionType}, {method.ActionParameterType}, {method.ActionResultType}>(");
		OutputActionParameterMapping(builder, method);
		builder.AddLine(");");

		builder.Unindent().AddLine("});");
	}

	private void OutputForRegular(CodeBuilder builder, MethodContext method)
	{
		string responseTOfType = _context.Types.ResponseT.Construct(method.ActionResultTypeSymbol).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

		builder.AddLine($"return await InternalWrapForError<{responseTOfType}>(async () =>");
		builder.AddLine("{").Indent();

		builder.Add($"{method.ActionResultType} actionResult = await Services.ExecuteAction<{method.ActionType}, {method.ActionParameterType}, {method.ActionResultType}>(");
		OutputActionParameterMapping(builder, method);
		builder.AddLine(");");

		builder.AddLine($"return new {responseTOfType}");
		builder.AddLine("{").Indent();
		builder.AddLine("IsSuccess = true,");
		builder.AddLine("Data = actionResult,");
		builder.Unindent().AddLine("};");

		builder.Unindent().AddLine("});");
	}

	private void OutputForFile(CodeBuilder builder, MethodContext method)
	{
		builder.Add($"return await FileAction<{method.ActionType}, {method.ActionParameterType}>(");
		OutputActionParameterMapping(builder, method);
		builder.AddLine(");");
	}

	private void OutputActionParameterMapping(CodeBuilder builder, MethodContext method)
	{
		List<MethodArgumentContext> mapArguments = method.Arguments.Where(x => string.IsNullOrEmpty(x.Name) == false).ToList();
		if (mapArguments.Count == 0)
		{
			builder.Add("new()");
			return;
		}

		builder.AddLine("new()");
		builder.AddLine("{").Indent();
		foreach (MethodArgumentContext argument in mapArguments)
		{
			builder.AddLine($"{argument.MapTo} = {argument.Name},");
		}

		builder.Unindent().Add("}");

	}
}