using Microsoft.CodeAnalysis.CSharp;
using Storm.Api.SourceGenerators.ActionMethods.Contexts;
using Storm.Api.SourceGenerators.Bases;

namespace Storm.Api.SourceGenerators.ActionMethods;

internal class CodeGenerator
{
	private readonly GeneratorContext _context;
	private readonly string _generatedCodeAttribute;

	private const string PROBLEM_MEDIA_TYPE = "application/problem+json";
	private const string SUCCESS_MEDIA_TYPE = "application/json";

	// Fully-qualified display names of framework types used in the generated code. These are non-generic,
	// non-nested types, so SymbolDisplayFormat.FullyQualifiedFormat is deterministically "global::<ns>.<Type>".
	// Hardcoding them keeps the cached model symbol-free (see source-generator-issue.md #1).
	private const string ENDPOINT_SUMMARY_ATTRIBUTE = "global::Microsoft.AspNetCore.Http.EndpointSummaryAttribute";
	private const string ENDPOINT_DESCRIPTION_ATTRIBUTE = "global::Microsoft.AspNetCore.Http.EndpointDescriptionAttribute";
	private const string PRODUCES_RESPONSE_TYPE_ATTRIBUTE = "global::Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute";
	private const string RESPONSE_TYPE = "global::Storm.Api.Dtos.Response";
	private const string OPEN_API_ERROR_CODES_ATTRIBUTE = "global::Storm.Api.OpenApis.OpenApiErrorCodesAttribute";
	private const string UNIT_TYPE = "global::Storm.Api.Unit";

	public CodeGenerator(GeneratorContext context, string generatedCodeAttribute)
	{
		_context = context;
		_generatedCodeAttribute = generatedCodeAttribute;
	}

	public string Generate()
	{
		CodeBuilder builder = new();

		builder.AddLine("// <auto-generated />");
		builder.AddLine("#nullable enable");
		builder.AddLine("using System.CodeDom.Compiler;");
		builder.AddLine("using Microsoft.AspNetCore.Mvc;");
		builder.AddLine("using Storm.Api.Extensions;");
		builder.AddLine();
		if (_context.Namespace is not null)
		{
			builder.AddLine($"namespace {_context.Namespace};");
		}
		builder.AddLine();
		builder.AddLine($"{SyntaxFacts.GetText(_context.ClassAccessibility)} partial class {_context.ClassName}");
		builder.AddLine("{").Indent();
		foreach (MethodContext method in _context.Methods)
		{
			if (method.Summary is not null)
			{
				builder.AddLine($"[{ENDPOINT_SUMMARY_ATTRIBUTE}(@\"{method.Summary}\")]");
			}

			string endpointDescription = "";
			if (method.ErrorCodes.Length > 0)
			{
				endpointDescription += "Error Codes:\n";
				foreach (ErrorCodeContext errorCode in method.ErrorCodes)
				{
					string errorDescription = errorCode.Description is not null ? $": {errorCode.Description}" : "";
					endpointDescription += $"- {errorCode.ErrorCode}{errorDescription}\n";
				}
				endpointDescription += "\n";
			}
			endpointDescription += method.Description ?? "";

			if (string.IsNullOrEmpty(endpointDescription) is false)
			{
				builder.AddLine($"[{ENDPOINT_DESCRIPTION_ATTRIBUTE}(@\"{endpointDescription}\")]");
			}

			string producesResponseTypeAttribute = PRODUCES_RESPONSE_TYPE_ATTRIBUTE;
			string mediaType = method.MediaType ?? SUCCESS_MEDIA_TYPE;

			if (method.SuccessStatusCodes.Length > 0)
			{
				foreach (StatusCodeContext successCodeContext in method.SuccessStatusCodes)
				{
					string description = successCodeContext.Description is not null ? $", Description = @\"{successCodeContext.Description}\"" : "";
					builder.AddLine($"[{producesResponseTypeAttribute}<{method.OpenApiReturnType}>({successCodeContext.StatusCode}, \"{mediaType}\"{description})]");
				}
			}
			else
			{
				builder.AddLine($"[{producesResponseTypeAttribute}<{method.OpenApiReturnType}>(200, \"{mediaType}\")]");
			}

			if (method.HttpErrorStatusCodes.Length > 0)
			{
				foreach (StatusCodeContext httpErrorContext in method.HttpErrorStatusCodes)
				{
					string description = httpErrorContext.Description is not null ? $", Description = @\"{httpErrorContext.Description}\"" : "";
					builder.AddLine($"[{producesResponseTypeAttribute}<{RESPONSE_TYPE}>({httpErrorContext.StatusCode}, \"{PROBLEM_MEDIA_TYPE}\"{description})]");
				}
			}

			if(method.ErrorCodes.Length > 0)
			{
				builder.AddLine($"[{OPEN_API_ERROR_CODES_ATTRIBUTE}({string.Join(", ", method.ErrorCodes.OrderBy(x => x.ErrorCode).Select(ec => $"\"{ec.ErrorCode}\""))})]");
			}

			builder.Add($"{SyntaxFacts.GetText(_context.ClassAccessibility)} partial async {method.ReturnType} {method.Name}(");
			builder.Add(string.Join(", ", method.Arguments.Select(p => $"{p.Type} {p.Name}")));
			builder.AddLine(")");
			builder.AddLine("{").Indent();

			if (method.Type is ActionType.File)
			{
				OutputForFile(builder, method);
			}
			else if (method.Type is ActionType.Unit)
			{
				OutputForUnit(builder, method);
			}
			else if (method.Type is ActionType.Response)
			{
				OutputForResponse(builder, method);
			}
			else if (method.Type is ActionType.Regular)
			{
				OutputForRegular(builder, method);
			}

			builder.Unindent().AddLine("}");

			builder.AddLine();
		}
		builder.Unindent().AddLine("}");

		return builder.Code();
	}

	private void OutputForUnit(CodeBuilder builder, MethodContext method)
	{
		builder.AddLine($"return await InternalWrapForError<{RESPONSE_TYPE}>(async () =>");
		builder.AddLine("{").Indent();

		builder.Add($"{method.ActionResultType} actionResult = await Services.ExecuteAction<{method.ActionType}, {method.ActionParameterType}, {method.ActionResultType}>(");
		OutputActionParameterMapping(builder, method);
		builder.AddLine(");");

		builder.AddLine($"return new {RESPONSE_TYPE}");
		builder.AddLine("{").Indent();
		builder.AddLine("IsSuccess = true,");
		builder.Unindent().AddLine("};");

		builder.Unindent().AddLine("});");
	}

	private void OutputForResponse(CodeBuilder builder, MethodContext method)
	{
		builder.AddLine($"return await InternalWrapForError<{method.ActionResultType}>(async () =>");
		builder.AddLine("{").Indent();

		builder.Add($"return await Services.ExecuteAction<{method.ActionType}, {method.ActionParameterType}, {method.ActionResultType}>(");
		OutputActionParameterMapping(builder, method);
		builder.AddLine(");");

		builder.Unindent().AddLine("});");
	}

	private void OutputForRegular(CodeBuilder builder, MethodContext method)
	{
		string responseTOfType = method.OpenApiReturnType;

		builder.AddLine($"return await InternalWrapForError<{responseTOfType}>(async () =>");
		builder.AddLine("{").Indent();

		builder.Add($"{method.ActionResultType} actionResult = await Services.ExecuteAction<{method.ActionType}, {method.ActionParameterType}, {method.ActionResultType}>(");
		OutputActionParameterMapping(builder, method);
		builder.AddLine(");");

		builder.AddLine($"return new {responseTOfType}");
		builder.AddLine("{").Indent();
		builder.AddLine("IsSuccess = true,");
		builder.AddLine("Data = actionResult,");
		builder.Unindent().AddLine("};");

		builder.Unindent().AddLine("});");
	}

	private void OutputForFile(CodeBuilder builder, MethodContext method)
	{
		builder.Add($"return await FileAction<{method.ActionType}, {method.ActionParameterType}>(");
		OutputActionParameterMapping(builder, method);
		builder.AddLine(");");
	}

	private void OutputActionParameterMapping(CodeBuilder builder, MethodContext method)
	{
		List<MethodArgumentContext> mapArguments = method.Arguments.Where(x => string.IsNullOrEmpty(x.Name) == false).ToList();
		if (mapArguments.Count == 0)
		{
			if (method.ActionParameterType == UNIT_TYPE)
			{
				builder.Add(method.ActionParameterType);
				builder.Add(".Default");
			}
			else
			{
				builder.Add("new()");
			}

			return;
		}

		builder.AddLine("new()");
		builder.AddLine("{").Indent();
		foreach (MethodArgumentContext argument in mapArguments)
		{
			builder.AddLine($"{argument.MapTo} = {argument.Name},");
		}

		builder.Unindent().Add("}");
	}
}