using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Storm.Api.SourceGenerators.ActionMethods;
using Storm.Api.SourceGenerators.Bases;

namespace Storm.Api.Tests.SourceGenerators;

public class BaseCodeGeneratorTests
{
	private static GeneratorDriver RunGenerator(BaseCodeGenerator gen, string? sourceCode = null)
	{
		CSharpCompilation compilation = CSharpCompilation.Create(
			"TestAssembly",
			sourceCode is null ? [] : [CSharpSyntaxTree.ParseText(sourceCode)],
			[MetadataReference.CreateFromFile(typeof(object).Assembly.Location)],
			new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

		GeneratorDriver driver = CSharpGeneratorDriver.Create(gen.AsSourceGenerator());
		return driver.RunGenerators(compilation);
	}

	private sealed class NoAttrGenerator : BaseCodeGenerator
	{
		protected override List<AttributeDefinition> Attributes { get; } = [];
	}

	private sealed class OneAttrGenerator : BaseCodeGenerator
	{
		protected override List<AttributeDefinition> Attributes { get; } =
		[
			new()
			{
				Name = "Demo",
				Targets = AttributeTargets.Class,
				AllowMultiple = true,
				Inherited = true,
			},
		];
	}

	private sealed class GenericClassAttrGenerator : BaseCodeGenerator
	{
		protected override List<AttributeDefinition> Attributes { get; } =
		[
			new()
			{
				Name = "Demo",
				Targets = AttributeTargets.Class,
				Generics =
				[
					new AttributeGenericDefinition { Name = "T", Constraints = new GenericConstraintDefinition { IsClass = true, HasNew = true } },
				],
			},
		];
	}

	private sealed class StructAttrGenerator : BaseCodeGenerator
	{
		protected override List<AttributeDefinition> Attributes { get; } =
		[
			new()
			{
				Name = "Demo",
				Targets = AttributeTargets.Class,
				Generics =
				[
					new AttributeGenericDefinition { Name = "T", Constraints = new GenericConstraintDefinition { IsStruct = true } },
				],
			},
		];
	}

	private sealed class TypeConstraintsAttrGenerator : BaseCodeGenerator
	{
		protected override List<AttributeDefinition> Attributes { get; } =
		[
			new()
			{
				Name = "Demo",
				Targets = AttributeTargets.Class,
				Generics =
				[
					new AttributeGenericDefinition { Name = "T", Constraints = new GenericConstraintDefinition { TypeConstraints = ["System.IDisposable"] } },
				],
			},
		];
	}

	private sealed class PropAttrGenerator : BaseCodeGenerator
	{
		protected override List<AttributeDefinition> Attributes { get; } =
		[
			new()
			{
				Name = "Demo",
				Targets = AttributeTargets.Class,
				Properties =
				[
					new AttributePropertyDefinition { Name = "Name", Type = typeof(string), InConstructor = false },
					new AttributePropertyDefinition { Name = "Count", Type = typeof(int), InConstructor = true },
				],
			},
		];
	}

	[Fact]
	public void Initialize_NoAttributes_RegistersNoPostInitOutput()
	{
		GeneratorDriver driver = RunGenerator(new NoAttrGenerator());
		GeneratorDriverRunResult result = driver.GetRunResult();
		result.GeneratedTrees.Should().BeEmpty();
	}

	[Fact]
	public void Initialize_WithAttributes_RegistersPostInitOutput()
	{
		GeneratorDriver driver = RunGenerator(new OneAttrGenerator());
		GeneratorDriverRunResult result = driver.GetRunResult();
		result.GeneratedTrees.Should().NotBeEmpty();
	}

	[Fact]
	public void AttributeClassGeneration_IncludesAutoGeneratedHeader()
	{
		string src = RunGenerator(new OneAttrGenerator()).GetRunResult().GeneratedTrees[0].ToString();
		src.Should().Contain("// <auto-generated />");
	}

	[Fact]
	public void AttributeClassGeneration_EmitsAttributeUsageTargets()
	{
		string src = RunGenerator(new OneAttrGenerator()).GetRunResult().GeneratedTrees[0].ToString();
		src.Should().Contain("AttributeUsage(AttributeTargets.Class");
	}

	[Fact]
	public void AttributeClassGeneration_EmitsInheritedAndAllowMultipleFlags()
	{
		string src = RunGenerator(new OneAttrGenerator()).GetRunResult().GeneratedTrees[0].ToString();
		src.Should().Contain("Inherited = true");
		src.Should().Contain("AllowMultiple = true");
	}

	[Fact]
	public void AttributeClassGeneration_AppliesGeneratedCodeAttribute()
	{
		string src = RunGenerator(new OneAttrGenerator()).GetRunResult().GeneratedTrees[0].ToString();
		src.Should().Contain("GeneratedCode(");
	}

	[Fact]
	public void AttributeClassGeneration_Generics_AppendsToClassName()
	{
		string src = RunGenerator(new GenericClassAttrGenerator()).GetRunResult().GeneratedTrees[0].ToString();
		src.Should().Contain("DemoAttribute<T>");
	}

	[Fact]
	public void AttributeClassGeneration_ClassConstraint_Emitted()
	{
		string src = RunGenerator(new GenericClassAttrGenerator()).GetRunResult().GeneratedTrees[0].ToString();
		src.Should().Contain("where T : class");
	}

	[Fact]
	public void AttributeClassGeneration_StructConstraint_Emitted()
	{
		string src = RunGenerator(new StructAttrGenerator()).GetRunResult().GeneratedTrees[0].ToString();
		src.Should().Contain("where T : struct");
	}

	[Fact]
	public void AttributeClassGeneration_NewConstraint_Emitted()
	{
		string src = RunGenerator(new GenericClassAttrGenerator()).GetRunResult().GeneratedTrees[0].ToString();
		src.Should().Contain("new()");
	}

	[Fact]
	public void AttributeClassGeneration_TypeConstraints_Emitted()
	{
		string src = RunGenerator(new TypeConstraintsAttrGenerator()).GetRunResult().GeneratedTrees[0].ToString();
		src.Should().Contain("System.IDisposable");
	}

	[Fact]
	public void AttributeClassGeneration_CombinedConstraints_EmittedInCorrectOrder()
	{
		string src = RunGenerator(new GenericClassAttrGenerator()).GetRunResult().GeneratedTrees[0].ToString();
		int classIdx = src.IndexOf("class");
		int newIdx = src.IndexOf("new()");
		classIdx.Should().BeLessThan(newIdx);
	}

	[Fact]
	public void AttributeClassGeneration_PropertiesWithInConstructorFalse_EmitsGetSetOnly()
	{
		string src = RunGenerator(new PropAttrGenerator()).GetRunResult().GeneratedTrees[0].ToString();
		src.Should().Contain("public System.String Name { get; set; }");
	}

	[Fact]
	public void AttributeClassGeneration_PropertiesWithInConstructorTrue_EmitsConstructor()
	{
		string src = RunGenerator(new PropAttrGenerator()).GetRunResult().GeneratedTrees[0].ToString();
		src.Should().Contain("public DemoAttribute(System.Int32 count)");
	}

	[Fact]
	public void AttributeClassGeneration_ConstructorArgumentName_IsCamelCased()
	{
		string src = RunGenerator(new PropAttrGenerator()).GetRunResult().GeneratedTrees[0].ToString();
		src.Should().Contain("Count = count");
	}

	[Fact]
	public void AttributeClassGeneration_FileName_UsesMetadataName()
	{
		GeneratorDriver driver = RunGenerator(new OneAttrGenerator());
		GeneratorDriverRunResult result = driver.GetRunResult();
		string fp = result.GeneratedTrees[0].FilePath;
		fp.Should().Contain("DemoAttribute");
		fp.Should().EndWith(".g.cs");
	}
}
