using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Storm.Api.SourceGenerators.ActionMethods;

namespace Storm.Api.Tests.SourceGenerators;

public class CodeGeneratorOutputTests
{
	private static MetadataReference[] References()
	{
		_ = typeof(Storm.Api.Unit);
		_ = typeof(Storm.Api.Dtos.Response);
		_ = typeof(Storm.Api.Dtos.Response<>);
		_ = typeof(Storm.Api.CQRS.IAction<,>);
		_ = typeof(Storm.Api.CQRS.Domains.Results.ApiFileResult);
		_ = typeof(Microsoft.AspNetCore.Mvc.IActionResult);
		_ = typeof(Microsoft.AspNetCore.Mvc.ActionResult<>);
		_ = typeof(Microsoft.AspNetCore.Mvc.FileResult);
		_ = typeof(Microsoft.AspNetCore.Mvc.ControllerBase);
		_ = typeof(Storm.Api.Controllers.BaseController);

		string trusted = (string)AppDomain.CurrentDomain.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!;
		HashSet<string> all = [.. trusted.Split(Path.PathSeparator)];
		foreach (System.Reflection.Assembly a in AppDomain.CurrentDomain.GetAssemblies())
		{
			if (!a.IsDynamic && !string.IsNullOrWhiteSpace(a.Location))
			{
				all.Add(a.Location);
			}
		}
		return all.Where(p => !string.IsNullOrWhiteSpace(p)).Select(p => (MetadataReference)MetadataReference.CreateFromFile(p)).ToArray();
	}

	private static string RunAndGetControllerOutput(string source, string controllerName = "MyController")
	{
		CSharpCompilation compilation = CSharpCompilation.Create(
			"T",
			[CSharpSyntaxTree.ParseText(source)],
			References(),
			new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
		GeneratorDriver driver = CSharpGeneratorDriver.Create(new ActionMethodCodeGenerator());
		GeneratorDriverRunResult result = driver.RunGenerators(compilation).GetRunResult();
		SyntaxTree? tree = result.GeneratedTrees.FirstOrDefault(t => t.FilePath.Contains(controllerName + ".Storm.Api.ActionMethods"));
		tree.Should().NotBeNull();
		return tree!.ToString();
	}

	private const string UnitAction = """
		using Storm.Api;
		using Storm.Api.CQRS;
		using Storm.Api.SourceGenerators.ActionMethods;

		namespace TestNs;

		public class UP {}
		public class UA : IAction<UP, Unit> { public System.Threading.Tasks.Task<Unit> Execute(UP p) => System.Threading.Tasks.Task.FromResult(Unit.Default); }

		public partial class MyController : Storm.Api.Controllers.BaseController
		{
			public MyController(System.IServiceProvider s) : base(s) {}
			[WithAction<UA>]
			public partial System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<Storm.Api.Dtos.Response>> Do();
		}
		""";

	private const string ResponseAction = """
		using Storm.Api.CQRS;
		using Storm.Api.Dtos;
		using Storm.Api.SourceGenerators.ActionMethods;

		namespace TestNs;

		public class RP {}
		public class RA : IAction<RP, Response<int>>
		{
			public System.Threading.Tasks.Task<Response<int>> Execute(RP p) => System.Threading.Tasks.Task.FromResult(new Response<int>());
		}

		public partial class MyController : Storm.Api.Controllers.BaseController
		{
			public MyController(System.IServiceProvider s) : base(s) {}
			[WithAction<RA>]
			public partial System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<Response<int>>> Do();
		}
		""";

	private const string RegularAction = """
		using Storm.Api.CQRS;
		using Storm.Api.SourceGenerators.ActionMethods;

		namespace TestNs;

		public class RegParam {}
		public class RegAction : IAction<RegParam, int> { public System.Threading.Tasks.Task<int> Execute(RegParam p) => System.Threading.Tasks.Task.FromResult(1); }

		public partial class MyController : Storm.Api.Controllers.BaseController
		{
			public MyController(System.IServiceProvider s) : base(s) {}
			[WithAction<RegAction>]
			public partial System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<Storm.Api.Dtos.Response<int>>> Do();
		}
		""";

	private const string FileAction = """
		using Storm.Api.CQRS;
		using Storm.Api.CQRS.Domains.Results;
		using Storm.Api.SourceGenerators.ActionMethods;

		namespace TestNs;

		public class FP {}
		public class FA : IAction<FP, ApiFileResult> { public System.Threading.Tasks.Task<ApiFileResult> Execute(FP p) => System.Threading.Tasks.Task.FromResult(ApiFileResult.Create(new byte[] {1}, "x")); }

		public partial class MyController : Storm.Api.Controllers.BaseController
		{
			public MyController(System.IServiceProvider s) : base(s) {}
			[WithAction<FA>]
			public partial System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> Do();
		}
		""";

	[Fact]
	public void Generate_OutputStartsWithAutoGeneratedHeader()
	{
		RunAndGetControllerOutput(UnitAction).Should().StartWith("// <auto-generated />");
	}

	[Fact]
	public void Generate_EmitsNullableEnableDirective()
	{
		RunAndGetControllerOutput(UnitAction).Should().Contain("#nullable enable");
	}

	[Fact]
	public void Generate_IncludesRequiredUsings()
	{
		string src = RunAndGetControllerOutput(UnitAction);
		src.Should().Contain("using Microsoft.AspNetCore.Mvc;");
		src.Should().Contain("using Storm.Api.Extensions;");
	}

	[Fact]
	public void Generate_EmitsNamespaceDeclaration_WhenNamespaceIsNotGlobal()
	{
		RunAndGetControllerOutput(UnitAction).Should().Contain("namespace TestNs;");
	}

	[Fact]
	public void Generate_OmitsNamespaceDeclaration_ForGlobalNamespace()
	{
		string src = UnitAction.Replace("namespace TestNs;", "");
		CSharpCompilation compilation = CSharpCompilation.Create("T", [CSharpSyntaxTree.ParseText(src)], References(), new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
		GeneratorDriver driver = CSharpGeneratorDriver.Create(new ActionMethodCodeGenerator());
		GeneratorDriverRunResult result = driver.RunGenerators(compilation).GetRunResult();
		SyntaxTree? tree = result.GeneratedTrees.FirstOrDefault(t => t.FilePath.Contains("MyController.Storm.Api.ActionMethods"));
		tree.Should().NotBeNull();
		tree!.ToString().Should().NotContain("namespace TestNs");
	}

	[Fact]
	public void Generate_EmitsPartialClassWrapper()
	{
		RunAndGetControllerOutput(UnitAction).Should().Contain("partial class MyController");
	}

	[Fact]
	public void Generate_UnitAction_ReturnsTaskActionResultOfResponse()
	{
		string src = RunAndGetControllerOutput(UnitAction);
		src.Should().Contain("InternalWrapForError");
		src.Should().Contain("IsSuccess = true");
	}

	[Fact]
	public void Generate_UnitAction_WrapsWithInternalWrapForError()
	{
		RunAndGetControllerOutput(UnitAction).Should().Contain("InternalWrapForError<");
	}

	[Fact]
	public void Generate_ResponseAction_ReturnsTaskActionResultOfResponse()
	{
		RunAndGetControllerOutput(ResponseAction).Should().Contain("InternalWrapForError<");
	}

	[Fact]
	public void Generate_RegularAction_ReturnsTaskActionResultOfResponseT()
	{
		string src = RunAndGetControllerOutput(RegularAction);
		src.Should().Contain("Response<");
	}

	[Fact]
	public void Generate_RegularAction_SetsDataAndIsSuccessTrue()
	{
		string src = RunAndGetControllerOutput(RegularAction);
		src.Should().Contain("Data = actionResult");
		src.Should().Contain("IsSuccess = true");
	}

	[Fact]
	public void Generate_FileAction_ReturnsTaskIActionResult_CallsFileAction()
	{
		RunAndGetControllerOutput(FileAction).Should().Contain("FileAction<");
	}

	[Fact]
	public void Generate_ZeroParameters_UsesUnitDefaultOrNew()
	{
		string src = RunAndGetControllerOutput(UnitAction);
		src.Should().Contain("new()");
	}

	[Fact]
	public void Generate_MethodIsAsync()
	{
		RunAndGetControllerOutput(UnitAction).Should().Contain(" async ");
	}

	[Fact]
	public void Generate_UsesServicesExecuteAction()
	{
		RunAndGetControllerOutput(UnitAction).Should().Contain("Services.ExecuteAction<");
	}

	private const string MappedParamsAction = """
		using Storm.Api.CQRS;
		using Storm.Api.SourceGenerators.ActionMethods;

		namespace TestNs;

		public class MP { public string Title { get; set; } = ""; }
		public class MA : IAction<MP, int> { public System.Threading.Tasks.Task<int> Execute(MP p) => System.Threading.Tasks.Task.FromResult(0); }

		public partial class MyController : Storm.Api.Controllers.BaseController
		{
			public MyController(System.IServiceProvider s) : base(s) {}
			[WithAction<MA>]
			public partial System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<Storm.Api.Dtos.Response<int>>> Do(string Title);
		}
		""";

	[Fact]
	public void Generate_MappedParameters_EmitsObjectInitializer()
	{
		string src = RunAndGetControllerOutput(MappedParamsAction);
		src.Should().Contain("new()");
		src.Should().Contain("Title = Title");
	}
}
